### PR TITLE
Add (un)install-user make target

### PR DESCRIPTION
**Pull request by SpotlightKid**
Prompted by @x42 remark on IRC.

Signed-off-by: Christopher Arndt <chris@chrisarndt.de>

### CODE REVIEW

**Comment by x42** [comment]
How is this different from `make install LV2DIR=$HOME/.lv2` ?

(and `make uninstall LV2DIR=$HOME/.lv2`)

**Comment by SpotlightKid** [comment]
The results are the same, but `make install-user` is quicker and easier to type and easier to tell somebody and to remember.

**Comment by SpotlightKid** [comment]
Ok, simplified the PR and also removed obsolete lines from `uninstall-bin` target.

**Comment by x42** [comment]
Since it's already possible to install in arbitrary custom LV2 folders, I think it would make more sense to offer an alternative to symlink the build.

Something like

```
USERLV2DIR ?= $HOME/lv2

userinstall-lv2:
  mkdir -p $(USERLV2DIR)
  ln -s `pwd`/build $(USERLV2DIR)/foobar/$(BUNDLE)
```

What do you think?

**Comment by x42** [comment]
> also removed obsolete lines from uninstall-bin target.

Nice. I've pulled these separately.

**Comment by SpotlightKid** [comment]
>  I think it would make more sense to offer an alternative to symlink the build.

My main motivation for this PR was to offer an easily rememberable way to install avldrums without root privileges, prompted by your remark on IRC:

> [23:08:13] -*- rgareus really ought to write an installer

But a way for developers to install the LV2 bundle during development would also be helpful. But I would name the target differently then, e.g. `install-link`.

**Comment by x42** [comment]
> [23:08:13] -*- rgareus really ought to write an installer

That was for binaries from https://x42-plugins.com/x42/x42-avldrums not from source.
Windows and Mac binaries have a installer GUI.

**Comment by SpotlightKid** [comment]
Closing this since I'm cleaning my unmerged PRs.

**Pull request closed without merging**
